# Generated by Django 6.0.5 on 2026-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('translated_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'translation cache entries',
            },
        ),
    ]
