"""
Django settings for beynunehcheh project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure--xa13!_4x+q4gzeqct-hi9(9mukffbr5&acj36uj)s$oyz8kav",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "10.0.0.107,localhost,127.0.0.1"
    ).split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'treebeard',
    'core',
    'gazette',
    'ibay',
    'search',
    'enrich',
    'catalog',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'beynunehcheh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'beynunehcheh.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url

_default_url = os.environ.get("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
_direct_url = os.environ.get("DATABASE_URL_DIRECT", _default_url)

DATABASES = {
    # Pooled in production (PgBouncer, transaction mode). Short web requests.
    "default": dj_database_url.parse(
        _default_url,
        conn_max_age=int(os.environ.get("DJANGO_CONN_MAX_AGE", "0")),
        disable_server_side_cursors=True,
    ),
    # Never pooled. Management commands stream over this alias and need real
    # server-side cursors; DDL cannot run through a transaction-mode pool.
    "direct": dj_database_url.parse(
        _direct_url,
        conn_max_age=0,
        disable_server_side_cursors=False,
    ),
}

# 'direct' is the same physical database as 'default', reached without the
# pooler. Saying so keeps the test runner from building a second, empty test
# database that a management command would read and find nothing in.
DATABASES["direct"]["TEST"] = {"MIRROR": "default"}

# Alias used for streaming reads in management commands. 'direct' bypasses the
# pooler so server-side cursors work over millions of rows. Tests point it at
# 'default', because a second connection cannot see an uncommitted test
# transaction -- streaming five rows exercises the same code either way.
STREAM_DB_ALIAS = os.environ.get("STREAM_DB_ALIAS", "direct")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} [{name}] {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'gazette': {'handlers': ['console'], 'level': 'INFO'},
        'ibay': {'handlers': ['console'], 'level': 'INFO'},
    },
}

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OLLAMA_URL = os.environ.get("OLLAMA_URL", "")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "gemma3:12b")

# --- search ---------------------------------------------------------------
# `dual` indexes fili-preserved lexemes at weight A and the consonant skeleton
# at weight C, so a correctly-filied query outranks a skeleton collision while
# a mis-filied one still matches. `skeleton` and `fili` exist so the strategy
# can be changed with a reindex rather than a migration. Spec 6.2.
SEARCH_DV_INDEX_MODE = os.environ.get("SEARCH_DV_INDEX_MODE", "dual")

SEARCH_RANKING = {
    "w_en": 1.0,
    "w_dv": 1.0,
    "w_latin": 0.6,
    "w_trigram": 0.4,
    "w_same_lang": 0.5,
    "w_freshness": 0.3,
    "w_quality": 0.2,
    "w_phrase": 0.5,
    "trigram_threshold": 0.25,
    "candidate_limit": 500,
    "freshness_half_life_days": {
        "news": 7,
        "job": 14,
        "shopping": 30,
        "property": 45,
    },
    "expired_penalty": 0.5,
}

# --- attachment extraction ------------------------------------------------
ATTACHMENT_FETCH_DELAY = float(os.environ.get("ATTACHMENT_FETCH_DELAY", "0.5"))
# Below this many extracted characters per page a PDF is treated as scanned.
SCANNED_CHARS_PER_PAGE = int(os.environ.get("SCANNED_CHARS_PER_PAGE", "200"))
TRANSCRIBE_MODEL = os.environ.get("TRANSCRIBE_MODEL", "claude-haiku-4-5")
TRANSCRIBE_MAX_PAGES = int(os.environ.get("TRANSCRIBE_MAX_PAGES", "10"))
# A 60-page document would emit ~90k output tokens against Haiku 4.5's 64k
# ceiling, so long documents are split. Correctness, not cost.
TRANSCRIBE_PAGES_PER_CHUNK = int(os.environ.get("TRANSCRIBE_PAGES_PER_CHUNK", "20"))
# Character error rate above which transcription output is rejected outright.
# Calibrated by the cer_harness command; text that is confidently wrong is
# worse than absent text.
TRANSCRIBE_MAX_CER = float(os.environ.get("TRANSCRIBE_MAX_CER", "0.15"))
# The anthropic SDK reads ANTHROPIC_API_KEY by default; accept CLAUDE_API_KEY
# as the project's canonical name so the env file is not confusing.
CLAUDE_API_KEY = os.environ.get("CLAUDE_API_KEY", "")

# --- Enrichment (spec 5.1, 4.3.2) ---
ENRICH_PROVIDER = os.getenv("ENRICH_PROVIDER", "deepseek")
ENRICH_MODEL = os.getenv("ENRICH_MODEL", "deepseek-v4-flash")
ENRICH_MODEL_ESCALATION = os.getenv("ENRICH_MODEL_ESCALATION", "deepseek-v4-pro")
ENRICH_MODEL_LOCAL = os.getenv("ENRICH_MODEL_LOCAL", "qwen3.5:4b")
ENRICH_CONCURRENCY = int(os.getenv("ENRICH_CONCURRENCY", "8"))
ENRICH_TIMEOUT = float(os.getenv("ENRICH_TIMEOUT", "120"))
# translate.py already caps gazette bodies at 3,500 chars; match it.
ENRICH_MAX_INPUT_CHARS = int(os.getenv("ENRICH_MAX_INPUT_CHARS", "3500"))

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY", "")
DEEPSEEK_BASE_URL = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")

# --- background field translation (P5 task 0C) ---
TRANSLATE_TIMEOUT = float(os.getenv("TRANSLATE_TIMEOUT", "30"))
TRANSLATE_MIN_CHARS = int(os.getenv("TRANSLATE_MIN_CHARS", "3"))
# Spec 5.5: English queries are translated to Dhivehi terms at query time.
SEARCH_TRANSLATE_QUERIES = os.getenv("SEARCH_TRANSLATE_QUERIES", "1") == "1"

# --- gettext catalog for closed vocabularies (P5 task 0C step 7) ---
USE_I18N = True
LANGUAGES = [("en", "English"), ("dv", "Dhivehi")]
LOCALE_PATHS = [BASE_DIR / "locale"]

# --- OCR for scanned attachments (spec 5.6, superseded rung 3) ---
GOOGLE_VISION_API_KEY = os.getenv("GOOGLE_VISION_API_KEY",
                                  os.getenv("VISION_API_KEY", ""))
OCR_DPI = int(os.getenv("OCR_DPI", "300"))
OCR_REPAIR_MODEL = os.getenv(
    "OCR_REPAIR_MODEL", "alakxender/t5-dhivehi-typo-corrector-asr"
)
# Below this the transcription is not describing the document it is attached
# to. Measured: 0% for a fabrication, 87% for a good page.
OCR_ANCHOR_MIN = float(os.getenv("OCR_ANCHOR_MIN", "0.30"))
OCR_CACHE_ENABLED = os.getenv("OCR_CACHE_ENABLED", "1") == "1"
OCR_CACHE_DIR = os.getenv("OCR_CACHE_DIR", str(BASE_DIR / ".cache" / "ocr"))
OCR_CACHE_SIZE_BYTES = int(os.getenv("OCR_CACHE_SIZE_BYTES", str(8 * 1024**3)))

# Maldives Retirement Pension Scheme. Settings, not constants, because tax
# treatment changes and hardcoding it is how a search engine starts lying.
# Spec 4.3.2.
PENSION_RATE = float(os.getenv("PENSION_RATE", "0.07"))
PENSION_BASE = os.getenv("PENSION_BASE", "basic")   # basic | gross
DEFAULT_WORKING_DAYS = int(os.getenv("DEFAULT_WORKING_DAYS", "20"))

# --- query and click logging (spec 16.3) ---
SEARCH_LOGGING_ENABLED = os.getenv("SEARCH_LOGGING_ENABLED", "1") == "1"
SEARCH_LOG_SALT = os.getenv("SEARCH_LOG_SALT", SECRET_KEY)
# Synchronous in tests: a thread pool plus pytest-django's transactional
# rollback is a race, not a test. conftest.py flips this on.
SEARCH_LOGGING_SYNC = False

# --- reports (spec 5.7) ---
REPORT_RATE_LIMIT = int(os.getenv("REPORT_RATE_LIMIT", "20"))
REPORT_RATE_WINDOW = int(os.getenv("REPORT_RATE_WINDOW", "3600"))

# Draft overlays run between adapter.to_document() and upsert. `search` knows
# only these dotted paths; it never imports `enrich`.
SEARCH_DRAFT_OVERLAYS = [
    "enrich.overlay.apply_enrichment",
]
# --- catalog identity (see catalog/identity.py::identity_stopwords) ---
# A model token appearing in this many For Sale listings or more names a
# platform, a capacity or a marketing claim, not a product. Measured DF:
# PS5 426, PS4 266, 5G 214, 256GB 163 against WH-1000XM5 2 and SQ905 1.
CATALOG_IDENTITY_STOPWORD_DF = int(os.getenv("CATALOG_IDENTITY_STOPWORD_DF", "15"))

# --- catalog (entity layer, spec section 19) ---
# How many linked listings feed one profile call. The union is what makes
# consensus possible; past a few dozen it is repetition paid for by the token.
CATALOG_PROFILE_MAX_LISTINGS = int(os.getenv("CATALOG_PROFILE_MAX_LISTINGS", "12"))
CATALOG_CONSENSUS_MIN_SELLERS = int(os.getenv("CATALOG_CONSENSUS_MIN_SELLERS", "2"))
CATALOG_INFERRED_MIN_CONFIDENCE = float(
    os.getenv("CATALOG_INFERRED_MIN_CONFIDENCE", "0.7"))
CATALOG_PROPOSAL_QUORUM = int(os.getenv("CATALOG_PROPOSAL_QUORUM", "3"))
CATALOG_PROPOSAL_MARGIN = int(os.getenv("CATALOG_PROPOSAL_MARGIN", "2"))
CATALOG_PROPOSAL_RATE_LIMIT = int(os.getenv("CATALOG_PROPOSAL_RATE_LIMIT", "20"))
CATALOG_PROPOSAL_RATE_WINDOW = int(os.getenv("CATALOG_PROPOSAL_RATE_WINDOW", "3600"))
