# Generated by Django 6.0.5 on 2026-05-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iulaan',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('office_name', models.CharField(max_length=255)),
                ('iulaan_type', models.CharField(max_length=255)),
                ('additional_info', models.JSONField()),
                ('attachments', models.JSONField()),
                ('body', models.TextField()),
            ],
        ),
    ]
