# Generated by Django 6.0.5 on 2026-05-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iulaan',
            name='translated_body',
            field=models.TextField(blank=True),
        ),
    ]
