# Generated by Django 6.0.5 on 2026-05-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0002_iulaan_translated_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='iulaan',
            name='translated_office_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='iulaan',
            name='translated_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
