# Generated by Django 6.0.5 on 2026-05-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0003_iulaan_translated_office_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IulaanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('translated_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('translated_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='iulaan',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='iulaan',
            name='translated_office_name',
        ),
        migrations.AlterField(
            model_name='iulaan',
            name='iulaan_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gazette.iulaantype'),
        ),
        migrations.AddField(
            model_name='iulaan',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gazette.office'),
        ),
    ]
