# Generated by Django 6.0.5 on 2026-05-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0004_iulaantype_office_remove_iulaan_office_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('translated_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'translation cache entries',
            },
        ),
    ]
