# Generated by Django 6.0.5 on 2026-08-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0005_translationcache'),
        ('core', '0002_copy_translation_cache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationCache',
        ),
    ]
