# Generated by Django 6.0.5 on 2026-08-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0006_delete_translationcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iulaan',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
