# Generated by Django 6.0.5 on 2026-08-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0007_iulaan_title_512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_raw', models.CharField(blank=True, max_length=512)),
                ('role', models.CharField(default='unknown', max_length=32)),
                ('url', models.URLField(max_length=1024)),
                ('content_sha', models.CharField(blank=True, max_length=64)),
                ('mime', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('chars_per_page', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('docx', 'docx'), ('pdftotext', 'pdftotext'), ('transcribed', 'transcribed'), ('none', 'none')], default='none', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('ocr_failed', 'ocr_failed'), ('fetch_failed', 'fetch_failed'), ('skipped', 'skipped')], default='pending', max_length=32)),
                ('transcribed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iulaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_files', to='gazette.iulaan')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='gazette_att_status_34714a_idx'), models.Index(fields=['iulaan', 'role'], name='gazette_att_iulaan__946b6d_idx')],
                'unique_together': {('iulaan', 'url')},
            },
        ),
    ]
