# Generated by Django 6.0.5 on 2026-08-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0008_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('ocr_failed', 'ocr_failed'), ('fetch_failed', 'fetch_failed'), ('extract_failed', 'extract_failed'), ('skipped', 'skipped')], default='pending', max_length=32),
        ),
    ]
