# Generated by Django 5.2.17 on 2026-08-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gazette', '0009_alter_attachment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iulaan',
            name='translated_title',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
