# Generated by Django 5.2.17 on 2026-08-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('search', '0012_searchdocument_category_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product', 'product'), ('service', 'service')], max_length=16)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(blank=True, max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128)),
                ('variant', models.CharField(blank=True, max_length=64)),
                ('service_type', models.CharField(blank=True, max_length=64)),
                ('provider_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title_en', models.CharField(blank=True, max_length=256)),
                ('title_dv', models.CharField(blank=True, max_length=256)),
                ('summary_en', models.CharField(blank=True, max_length=240)),
                ('summary_dv', models.CharField(blank=True, max_length=240)),
                ('identity_confidence', models.FloatField(default=0.0)),
                ('profile_status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('needs_review', 'needs review'), ('failed', 'failed')], default='pending', max_length=16)),
                ('profile_prompt_version', models.IntegerField(default=0)),
                ('profile_error', models.TextField(blank=True)),
                ('listing_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='search.category')),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='EntityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_raw', models.CharField(max_length=64)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('provenance', models.CharField(choices=[('scraped', 'scraped from the source'), ('correction', 'crowdsourced correction'), ('consensus', 'agreed across listings'), ('grounded', 'found in listing text'), ('inferred', 'model knowledge')], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('support_count', models.IntegerField(default=1)),
                ('is_winner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='catalog.entity')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_values', to='search.speckey')),
            ],
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_key', models.CharField(max_length=128)),
                ('method', models.CharField(choices=[('identity_match', 'identity match'), ('seller_service', 'seller and service'), ('manual', 'manual')], max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.entity')),
            ],
        ),
        migrations.CreateModel(
            name='FieldProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_raw', models.CharField(max_length=64)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('proposer_ip_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('applied', 'applied'), ('rejected', 'rejected'), ('conflicted', 'conflicted')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='catalog.entity')),
            ],
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['kind', 'profile_status'], name='entity_kind_status'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['-listing_count'], name='entity_listing_count'),
        ),
        migrations.AddIndex(
            model_name='entityfield',
            index=models.Index(fields=['entity', 'is_winner'], name='entityfield_winner'),
        ),
        migrations.AddIndex(
            model_name='entityfield',
            index=models.Index(fields=['key_raw'], name='entityfield_key_raw'),
        ),
        migrations.AddConstraint(
            model_name='entityfield',
            constraint=models.UniqueConstraint(fields=('entity', 'key_raw', 'provenance', 'value_num', 'value_text'), name='uniq_entityfield_value', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='entitylink',
            index=models.Index(fields=['entity'], name='entitylink_entity'),
        ),
        migrations.AddConstraint(
            model_name='entitylink',
            constraint=models.UniqueConstraint(fields=('source', 'source_key'), name='uniq_entitylink_document'),
        ),
        migrations.AddIndex(
            model_name='fieldproposal',
            index=models.Index(fields=['status', '-created_at'], name='proposal_status_created'),
        ),
        migrations.AddIndex(
            model_name='fieldproposal',
            index=models.Index(fields=['entity', 'key_raw'], name='proposal_field'),
        ),
        migrations.AddConstraint(
            model_name='fieldproposal',
            constraint=models.UniqueConstraint(fields=('entity', 'key_raw', 'value_num', 'value_text', 'proposer_ip_hash'), name='uniq_proposal_per_proposer', nulls_distinct=False),
        ),
    ]
