# Generated by Django 6.0.5 on 2026-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_key', models.CharField(max_length=128)),
                ('content_hash', models.CharField(max_length=64)),
                ('doc_type', models.CharField(max_length=32)),
                ('doc_type_confidence', models.FloatField(default=0.0)),
                ('canonical_title_en', models.CharField(blank=True, max_length=512)),
                ('canonical_title_dv', models.CharField(blank=True, max_length=512)),
                ('summary_en', models.CharField(blank=True, max_length=240)),
                ('summary_dv', models.CharField(blank=True, max_length=240)),
                ('attrs', models.JSONField(blank=True, default=dict)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.IntegerField(default=0)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ok', 'ok'), ('needs_review', 'needs review'), ('failed', 'failed')], default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status'], name='enriched_source_status'), models.Index(fields=['content_hash'], name='enriched_content_hash')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_key'), name='uniq_enriched_source_key')],
            },
        ),
    ]
