# Generated by Django 6.0.5 on 2026-08-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True)),
                ('label_en', models.CharField(max_length=64)),
                ('label_dv', models.CharField(blank=True, max_length=64)),
                ('site_url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=128)),
                ('icon_fallback_text', models.CharField(blank=True, max_length=4)),
                ('accent', models.CharField(blank=True, max_length=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
