import django.contrib.postgres.search
from django.db import migrations, models

CREATE = r"""
CREATE TABLE search_searchdocument (
    id              bigint GENERATED BY DEFAULT AS IDENTITY,
    source          varchar(32)  NOT NULL,
    source_key      varchar(128) NOT NULL,
    doc_type        varchar(32)  NOT NULL,
    url             varchar(512) NOT NULL,
    title_en        varchar(512) NOT NULL DEFAULT '',
    title_dv        varchar(512) NOT NULL DEFAULT '',
    title_latin     varchar(512) NOT NULL DEFAULT '',
    summary_en      text         NOT NULL DEFAULT '',
    summary_dv      text         NOT NULL DEFAULT '',
    vector_en       tsvector,
    vector_dv       tsvector,
    vector_latin    tsvector,
    price           numeric(12,2),
    currency        varchar(8)   NOT NULL DEFAULT 'MVR',
    location        varchar(128) NOT NULL DEFAULT '',
    island          varchar(128) NOT NULL DEFAULT '',
    atoll           varchar(64)  NOT NULL DEFAULT '',
    published_at    timestamptz,
    expires_at      timestamptz,
    is_active       boolean      NOT NULL DEFAULT true,
    attrs           jsonb        NOT NULL DEFAULT '{}'::jsonb,
    card            jsonb        NOT NULL DEFAULT '{}'::jsonb,
    card_version    integer      NOT NULL DEFAULT 1,
    thumbnails      jsonb        NOT NULL DEFAULT '[]'::jsonb,
    quality         double precision NOT NULL DEFAULT 0,
    content_hash    varchar(64)  NOT NULL DEFAULT '',
    indexed_at      timestamptz  NOT NULL DEFAULT now(),
    stale_marked_at timestamptz,
    -- The partition key must be in every unique constraint on a partitioned
    -- table. `source` is immutable and already part of identity, so this is
    -- free; `doc_type` is mutable and must never appear here. Spec 12.2.
    PRIMARY KEY (id, source),
    CONSTRAINT uniq_source_source_key UNIQUE (source, source_key)
) PARTITION BY LIST (source);

CREATE TABLE search_searchdocument_gazette
    PARTITION OF search_searchdocument FOR VALUES IN ('gazette');
CREATE TABLE search_searchdocument_default
    PARTITION OF search_searchdocument DEFAULT;

-- All GIN indexes are partial on is_active: dead listings accumulate forever
-- and nobody searches them. Spec 12.2.
CREATE INDEX sd_vec_en_gin  ON search_searchdocument USING gin (vector_en)
    WHERE is_active;
CREATE INDEX sd_vec_dv_gin  ON search_searchdocument USING gin (vector_dv)
    WHERE is_active;
CREATE INDEX sd_vec_lat_gin ON search_searchdocument USING gin (vector_latin)
    WHERE is_active;
CREATE INDEX sd_attrs_gin   ON search_searchdocument USING gin (attrs jsonb_path_ops)
    WHERE is_active;

-- Trigram on titles only. On body text these indexes would dominate the
-- database, since they store every three-character window. Spec 12.1.
CREATE INDEX sd_title_en_trgm  ON search_searchdocument
    USING gin (title_en gin_trgm_ops) WHERE is_active;
CREATE INDEX sd_title_dv_trgm  ON search_searchdocument
    USING gin (title_dv gin_trgm_ops) WHERE is_active;
CREATE INDEX sd_title_lat_trgm ON search_searchdocument
    USING gin (title_latin gin_trgm_ops) WHERE is_active;

CREATE INDEX sd_published_brin ON search_searchdocument USING brin (published_at);
CREATE INDEX sd_type_published ON search_searchdocument (doc_type, published_at DESC)
    WHERE is_active;
CREATE INDEX sd_price          ON search_searchdocument (price) WHERE is_active;
CREATE INDEX sd_expires        ON search_searchdocument (expires_at) WHERE is_active;
CREATE INDEX sd_stale          ON search_searchdocument (stale_marked_at)
    WHERE stale_marked_at IS NOT NULL;
"""

DROP = "DROP TABLE IF EXISTS search_searchdocument CASCADE;"


class Migration(migrations.Migration):
    dependencies = [("search", "0001_initial")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(CREATE, DROP)],
            state_operations=[
                migrations.CreateModel(
                    name="SearchDocument",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("source", models.CharField(max_length=32)),
                        ("source_key", models.CharField(max_length=128)),
                        ("doc_type", models.CharField(max_length=32)),
                        ("url", models.URLField(max_length=512)),
                        ("title_en", models.CharField(blank=True, max_length=512)),
                        ("title_dv", models.CharField(blank=True, max_length=512)),
                        ("title_latin", models.CharField(blank=True, max_length=512)),
                        ("summary_en", models.TextField(blank=True)),
                        ("summary_dv", models.TextField(blank=True)),
                        ("vector_en", django.contrib.postgres.search.SearchVectorField(null=True)),
                        ("vector_dv", django.contrib.postgres.search.SearchVectorField(null=True)),
                        ("vector_latin", django.contrib.postgres.search.SearchVectorField(null=True)),
                        ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                        ("currency", models.CharField(default="MVR", max_length=8)),
                        ("location", models.CharField(blank=True, max_length=128)),
                        ("island", models.CharField(blank=True, max_length=128)),
                        ("atoll", models.CharField(blank=True, max_length=64)),
                        ("published_at", models.DateTimeField(blank=True, null=True)),
                        ("expires_at", models.DateTimeField(blank=True, null=True)),
                        ("is_active", models.BooleanField(default=True)),
                        ("attrs", models.JSONField(blank=True, default=dict)),
                        ("card", models.JSONField(blank=True, default=dict)),
                        ("card_version", models.IntegerField(default=1)),
                        ("thumbnails", models.JSONField(blank=True, default=list)),
                        ("quality", models.FloatField(default=0.0)),
                        ("content_hash", models.CharField(blank=True, max_length=64)),
                        ("indexed_at", models.DateTimeField(auto_now=True)),
                        ("stale_marked_at", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "search_searchdocument",
                        "constraints": [models.UniqueConstraint(fields=("source", "source_key"), name="uniq_source_source_key")],
                    },
                ),
            ],
        )
    ]
