# Generated by Django 6.0.5 on 2026-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_seed_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=128, unique=True)),
                ('expands_to', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name_plural': 'query aliases',
                'ordering': ['term'],
            },
        ),
    ]
