# Generated by Django 5.2.17 on 2026-08-18 06:36

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_queryalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=64, unique=True)),
                ('frequency', models.IntegerField(default=0)),
                ('script', models.CharField(max_length=8)),
                ('doc_type', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['-frequency'], name='suggest_freq')],
            },
        ),
        migrations.AddIndex(
            model_name="suggestterm",
            index=GinIndex(fields=["term"], name="suggest_term_trgm",
                           opclasses=["gin_trgm_ops"]),
        ),
    ]
