# Generated by Django 5.2.17 on 2026-08-18 06:39

import django.db.models.deletion
from django.db import migrations, models

CREATE = r"""
CREATE TABLE search_querylog (
    id             bigserial,
    q_raw          varchar(256) NOT NULL,
    q_normalized   varchar(256) NOT NULL DEFAULT '',
    detected_lang  varchar(8)   NOT NULL DEFAULT '',
    response_lang  varchar(8)   NOT NULL DEFAULT '',
    doc_type       varchar(32)  NOT NULL DEFAULT '',
    filters        jsonb        NOT NULL DEFAULT '[]'::jsonb,
    result_count   integer      NOT NULL DEFAULT 0,
    latency_ms     integer      NOT NULL DEFAULT 0,
    session_hash   varchar(64)  NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE search_clicklog (
    id          bigserial,
    query_id    bigint      NOT NULL,
    document_id bigint      NOT NULL,
    position    integer     NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- A default partition means an insert never fails because nobody ran the
-- monthly command. Rows land here and get moved when the real partition is
-- created; losing a click because of a missed cron is not acceptable.
CREATE TABLE search_querylog_default PARTITION OF search_querylog DEFAULT;
CREATE TABLE search_clicklog_default PARTITION OF search_clicklog DEFAULT;

-- BRIN, not btree: these tables are append-only and physically ordered by
-- created_at, which is exactly the access pattern BRIN is for, at roughly
-- 1/1000th the size.
CREATE INDEX querylog_created_brin ON search_querylog USING brin (created_at);
CREATE INDEX clicklog_created_brin ON search_clicklog USING brin (created_at);
CREATE INDEX querylog_zero_results ON search_querylog (created_at)
    WHERE result_count = 0;
CREATE INDEX clicklog_query ON search_clicklog (query_id);
"""

DROP = "DROP TABLE IF EXISTS search_querylog CASCADE; DROP TABLE IF EXISTS search_clicklog CASCADE;"


def _ensure_partitions(apps, schema_editor):
    from search.management.commands.create_log_partitions import create_partitions
    create_partitions(months=4)


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_suggestterm'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(CREATE, DROP)],
            state_operations=[
                migrations.CreateModel(
                    name='QueryLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('q_raw', models.CharField(max_length=256)),
                        ('q_normalized', models.CharField(blank=True, max_length=256)),
                        ('detected_lang', models.CharField(blank=True, max_length=8)),
                        ('response_lang', models.CharField(blank=True, max_length=8)),
                        ('doc_type', models.CharField(blank=True, max_length=32)),
                        ('filters', models.JSONField(blank=True, default=list)),
                        ('result_count', models.IntegerField(default=0)),
                        ('latency_ms', models.IntegerField(default=0)),
                        ('session_hash', models.CharField(max_length=64)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'search_querylog',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='ClickLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.IntegerField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clicks', to='search.searchdocument')),
                        ('query', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='search.querylog')),
                    ],
                    options={
                        'db_table': 'search_clicklog',
                        'managed': True,
                    },
                ),
            ],
        ),
        migrations.RunPython(_ensure_partitions, migrations.RunPython.noop),
    ]
