# Generated by Django 5.2.17 on 2026-08-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_querylog_clicklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('stale', 'stale'), ('wrong_details', 'wrong details'), ('dead_link', 'dead link'), ('spam', 'spam'), ('other', 'other')], max_length=24)),
                ('note', models.TextField(blank=True)),
                ('reporter_ip_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'open'), ('actioned', 'actioned'), ('rejected', 'rejected')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reports', to='search.searchdocument')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='report_status_created')],
                'constraints': [models.UniqueConstraint(fields=('document', 'reason', 'reporter_ip_hash'), name='uniq_report_per_reporter_reason')],
            },
        ),
    ]
