# Generated by Django 5.2.17 on 2026-08-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_documentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label_en', models.CharField(max_length=64)),
                ('label_dv', models.CharField(blank=True, max_length=64)),
                ('datatype', models.CharField(choices=[('numeric', 'numeric'), ('enum', 'enum'), ('bool', 'bool')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('unit_aliases', models.JSONField(blank=True, default=list)),
                ('value_aliases', models.JSONField(blank=True, default=dict)),
                ('widget', models.CharField(choices=[('range', 'range'), ('checkbox', 'checkbox'), ('toggle', 'toggle')], default='checkbox', max_length=16)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(default=100)),
                ('is_facetable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'key'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_raw', models.CharField(max_length=64)),
                ('value_num', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='specs', to='search.searchdocument')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='search.speckey')),
            ],
            options={
                'indexes': [models.Index(fields=['document'], name='docspec_document'), models.Index(fields=['key', 'value_text'], name='docspec_key_text'), models.Index(fields=['key', 'value_num'], name='docspec_key_num'), models.Index(fields=['key_raw'], name='docspec_key_raw')],
                'constraints': [models.UniqueConstraint(fields=('document', 'key_raw', 'value_num', 'value_text'), name='uniq_documentspec_value', nulls_distinct=False)],
            },
        ),
    ]
