# Generated by Django 5.2.17 on 2026-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_speckey_documentspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='category_leaf',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
