# Generated by Django 5.2.17 on 2026-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_searchdocument_category_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='duplicate_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS sd_dedupe_key ON search_searchdocument "
                "(dedupe_key) WHERE dedupe_key <> '';",
            reverse_sql="DROP INDEX IF EXISTS sd_dedupe_key;",
        ),
    ]
