# Generated by Django 5.2.17 on 2026-08-19 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_searchdocument_dedupe_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label_en', models.CharField(max_length=128)),
                ('label_dv', models.CharField(blank=True, max_length=128)),
                ('tier', models.CharField(choices=[('family', 'family'), ('primary', 'primary product'), ('accessory', 'accessory'), ('part', 'part'), ('service', 'service')], max_length=16)),
                ('doc_type', models.CharField(blank=True, max_length=32)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='search.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SourceCategoryMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('path', models.JSONField(default=list)),
                ('path_key', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=256)),
                ('document_count', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_paths', to='search.category')),
            ],
            options={
                'indexes': [models.Index(fields=['source', '-document_count'], name='sourcecat_source_count')],
                'constraints': [models.UniqueConstraint(fields=('source', 'path_key'), name='uniq_sourcecategory_path')],
            },
        ),
    ]
