# Generated by Django 5.2.17 on 2026-08-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_category_sourcecategorymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='search.category'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='contact_phone',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
