# Generated by Django 5.2.17 on 2026-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_searchdocument_category_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentspec',
            name='provenance',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
    ]
