# Generated by Django 5.2.17 on 2026-08-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_documentspec_provenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('source_key', models.CharField(max_length=128)),
                ('target_field', models.CharField(max_length=32)),
                ('source_field', models.CharField(max_length=32)),
                ('source_hash', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'source_key'], name='field_translation_doc')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_key', 'target_field'), name='field_translation_unique')],
            },
        ),
    ]
